# =====================================================================
# Category Definitions and Constraints
# =====================================================================
CATEGORIES = {
    "ja": {
        "transport": "🚗 移動・交通",
        "living":    "🍽️ 生活・環境",
        "wellbeing": "💖 心身の健康",
        "leisure":   "🎉 余暇・エンタメ",
        "learning":  "📚 自己研鑽",
    },
    "en": {
        "transport": "🚗 Transport",
        "living":    "🍽️ Living & Dining",
        "wellbeing": "💖 Well-being",
        "leisure":   "🎉 Leisure & Play",
        "learning":  "📚 Growth & Learning",
    }
}

CATEGORY_CONSTRAINTS = {
    "transport": {"or_tools_min": 1, "or_tools_max": 1,
                  "label_ja": "必須: 1つ選択（パッケージ）", "label_en": "Required: Choose 1 package"},
    "living":    {"or_tools_min": 0, "or_tools_max": 99,
                  "label_ja": "推奨: 1〜3つ", "label_en": "Recommended: 1-3"},
    "wellbeing": {"or_tools_min": 0, "or_tools_max": 99,
                  "label_ja": "推奨: 1〜2つ", "label_en": "Recommended: 1-2"},
    "leisure":   {"or_tools_min": 0, "or_tools_max": 99,
                  "label_ja": "推奨: 1〜3つ", "label_en": "Recommended: 1-3"},
    "learning":  {"or_tools_min": 0, "or_tools_max": 99,
                  "label_ja": "推奨: 1〜2つ", "label_en": "Recommended: 1-2"},
}

# =====================================================================
# Default Items List (Refined and Integrated)
# =====================================================================
DEFAULT_ITEMS = [
    # ── 1. Transport ────────────────────────────
    {"category": "transport", "priority": 2,
     "name_ja": "車メイン", "name_en": "Car (Primary)",
     "initial_cost": 25000, "monthly_cost": 650,
     "health": 0, "connections": 3, "freedom": 10, "growth": 1,
     "note_ja": "車両＋保険$120＋ガス$150＋駐車場等込み", "note_en": "Includes Vehicle, Insurance$120, Gas, etc."},
    {"category": "transport", "priority": 4,
     "name_ja": "バイクメイン", "name_en": "Motorcycle (Primary)",
     "initial_cost": 5000, "monthly_cost": 120,
     "health": 2, "connections": 4, "freedom": 8, "growth": 2,
     "note_ja": "車両$5000＋維持費(保険・ガス)$120", "note_en": "Vehicle$5000 + Maintenance$120"},
    {"category": "transport", "priority": 3,
     "name_ja": "カーシェア＋自転車", "name_en": "Car Share + Bicycle",
     "initial_cost": 500, "monthly_cost": 130,
     "health": 6, "connections": 3, "freedom": 5, "growth": 3,
     "note_ja": "カーシェア$100＋自転車維持$30", "note_en": "Car share$100 + Bicycle upkeep$30"},
    {"category": "transport", "priority": 4,
     "name_ja": "電動自転車＋Uber", "name_en": "E-Bike + Uber",
     "initial_cost": 2000, "monthly_cost": 160,
     "health": 5, "connections": 2, "freedom": 5, "growth": 2,
     "note_ja": "電動自転車維持$10＋Uber$150", "note_en": "E-Bike upkeep$10 + Uber$150"},
    {"category": "transport", "priority": 5,
     "name_ja": "公共交通メイン", "name_en": "Public Transit",
     "initial_cost": 0, "monthly_cost": 80,
     "health": 4, "connections": 4, "freedom": 2, "growth": 1,
     "note_ja": "定期券・バス等", "note_en": "Pass / Bus etc."},
    {"category": "transport", "priority": 6,
     "name_ja": "自転車のみ", "name_en": "Bicycle Only",
     "initial_cost": 500, "monthly_cost": 10,
     "health": 9, "connections": 2, "freedom": 4, "growth": 3,
     "note_ja": "健康効果最大", "note_en": "Maximum health benefits"},
    {"category": "transport", "priority": 7,
     "name_ja": "Uberのみ", "name_en": "Uber/Lyft Only",
     "initial_cost": 0, "monthly_cost": 250,
     "health": 0, "connections": 2, "freedom": 5, "growth": 2,
     "note_ja": "移動時間を有効活用", "note_en": "Efficient use of travel time"},

    # ── 2. Living & Dining ────────────────────────────
    {"category": "living", "priority": 1,
     "name_ja": "外食メイン（ディナー等）", "name_en": "Dining Out (Primary)",
     "initial_cost": 0, "monthly_cost": 200,
     "health": -2, "connections": 8, "freedom": 5, "growth": 2, "note_ja": "", "note_en": ""},
    {"category": "living", "priority": 2,
     "name_ja": "コーヒー・カフェ代", "name_en": "Coffee / Cafe",
     "initial_cost": 0, "monthly_cost": 60,
     "health": -1, "connections": 4, "freedom": 3, "growth": 2, "note_ja": "", "note_en": ""},
    {"category": "living", "priority": 3,
     "name_ja": "食材宅配サービス", "name_en": "Meal Kit Delivery",
     "initial_cost": 0, "monthly_cost": 150,
     "health": 6, "connections": 2, "freedom": 4, "growth": 3, "note_ja": "買い物・調理の時短", "note_en": "Saves shopping/cooking time"},
    {"category": "living", "priority": 4,
     "name_ja": "エルゴノミクスチェア", "name_en": "Ergonomic Chair",
     "initial_cost": 600, "monthly_cost": 0,
     "health": 7, "connections": 0, "freedom": 2, "growth": 4, "note_ja": "腰痛予防・在宅ワークの質向上", "note_en": "Prevents back pain, improves WFH quality"},
    {"category": "living", "priority": 5,
     "name_ja": "高級マットレス・寝具", "name_en": "Premium Mattress",
     "initial_cost": 1000, "monthly_cost": 0,
     "health": 9, "connections": 0, "freedom": 1, "growth": 2, "note_ja": "睡眠の質向上", "note_en": "Improves sleep quality"},
    {"category": "living", "priority": 6,
     "name_ja": "時短家電（食洗機・ルンバ等）", "name_en": "Time-saving Appliances",
     "initial_cost": 800, "monthly_cost": 0,
     "health": 2, "connections": 1, "freedom": 8, "growth": 1, "note_ja": "家事時間を削減", "note_en": "Reduces chore time"},
    {"category": "living", "priority": 7,
     "name_ja": "家事代行サービス（月2回）", "name_en": "Housekeeping Service",
     "initial_cost": 0, "monthly_cost": 150,
     "health": 3, "connections": 0, "freedom": 9, "growth": 1, "note_ja": "時間と心の余裕", "note_en": "Frees up time and mental space"},

    # ── 3. Well-being ────────────────────────────
    {"category": "wellbeing", "priority": 1,
     "name_ja": "ジム・ヨガスタジオ", "name_en": "Gym / Yoga",
     "initial_cost": 100, "monthly_cost": 60,
     "health": 9, "connections": 5, "freedom": -1, "growth": 4, "note_ja": "入会金＋月会費", "note_en": "Enrollment + monthly fee"},
    {"category": "wellbeing", "priority": 2,
     "name_ja": "パーソナルトレーナー", "name_en": "Personal Trainer",
     "initial_cost": 0, "monthly_cost": 200,
     "health": 10, "connections": 4, "freedom": -3, "growth": 7, "note_ja": "高コストだがリターン大", "note_en": "High cost, high return"},
    {"category": "wellbeing", "priority": 3,
     "name_ja": "サプリメント・健康食品", "name_en": "Supplements",
     "initial_cost": 0, "monthly_cost": 20,
     "health": 6, "connections": 0, "freedom": 2, "growth": 1, "note_ja": "日常的な健康維持", "note_en": "Daily health maintenance"},
    {"category": "wellbeing", "priority": 4,
     "name_ja": "メンタルケア・カウンセリング", "name_en": "Therapy / Counseling",
     "initial_cost": 0, "monthly_cost": 150,
     "health": 8, "connections": 3, "freedom": 6, "growth": 8, "note_ja": "精神的なレジリエンス向上", "note_en": "Improves mental resilience"},
    {"category": "wellbeing", "priority": 5,
     "name_ja": "マッサージ・スパ・サウナ", "name_en": "Massage / Spa / Sauna",
     "initial_cost": 0, "monthly_cost": 80,
     "health": 6, "connections": 2, "freedom": 2, "growth": 2, "note_ja": "フィジカルのメンテナンス", "note_en": "Physical maintenance"},
    {"category": "wellbeing", "priority": 6,
     "name_ja": "旅行・リトリート積立", "name_en": "Travel / Retreat Fund",
     "initial_cost": 0, "monthly_cost": 150,
     "health": 3, "connections": 7, "freedom": 9, "growth": 7, "note_ja": "非日常によるリフレッシュ", "note_en": "Refresh through extraordinary experiences"},
    {"category": "wellbeing", "priority": 7,
     "name_ja": "ペット", "name_en": "Pet",
     "initial_cost": 500, "monthly_cost": 100,
     "health": 5, "connections": 7, "freedom": -5, "growth": 3, "note_ja": "孤独感解消。旅行に制約", "note_en": "Cures loneliness, restricts travel"},

    # ── 4. Leisure & Play ────────────────────────────
    {"category": "leisure", "priority": 1,
     "name_ja": "交際費・飲み代", "name_en": "Socializing / Drinks",
     "initial_cost": 0, "monthly_cost": 150,
     "health": -2, "connections": 10, "freedom": 2, "growth": 2, "note_ja": "過度な飲酒は健康に影響", "note_en": "Excess affects health"},
    {"category": "leisure", "priority": 2,
     "name_ja": "動画・音楽サブスク", "name_en": "Streaming Subscriptions",
     "initial_cost": 0, "monthly_cost": 30,
     "health": -1, "connections": 2, "freedom": 3, "growth": 1, "note_ja": "Netflix, Spotify等", "note_en": "Netflix, Spotify etc."},
    {"category": "leisure", "priority": 3,
     "name_ja": "ゲーム", "name_en": "Gaming",
     "initial_cost": 500, "monthly_cost": 20,
     "health": -3, "connections": 4, "freedom": 2, "growth": 2, "note_ja": "長時間プレイは健康に影響", "note_en": "Extended play affects health"},
    {"category": "leisure", "priority": 4,
     "name_ja": "アウトドア・スポーツ", "name_en": "Outdoor / Sports",
     "initial_cost": 300, "monthly_cost": 50,
     "health": 7, "connections": 6, "freedom": 7, "growth": 5, "note_ja": "キャンプ、ハイキング等", "note_en": "Camping, Hiking etc."},
    {"category": "leisure", "priority": 5,
     "name_ja": "ファッション・美容", "name_en": "Fashion / Beauty",
     "initial_cost": 0, "monthly_cost": 100,
     "health": 1, "connections": 4, "freedom": 2, "growth": 2, "note_ja": "自己表現と自信", "note_en": "Self-expression and confidence"},
    {"category": "leisure", "priority": 6,
     "name_ja": "映画・観劇・美術館", "name_en": "Movies / Arts / Events",
     "initial_cost": 0, "monthly_cost": 60,
     "health": 1, "connections": 3, "freedom": 4, "growth": 5, "note_ja": "文化的なインプット", "note_en": "Cultural input"},
    {"category": "leisure", "priority": 7,
     "name_ja": "クリエイティブな趣味", "name_en": "Creative Hobbies",
     "initial_cost": 200, "monthly_cost": 40,
     "health": 2, "connections": 2, "freedom": 6, "growth": 7, "note_ja": "DIY、アート、音楽制作等", "note_en": "DIY, Art, Music production etc."},
    {"category": "leisure", "priority": 8,
     "name_ja": "推し活・ファンコミュニティ", "name_en": "Fandom / Communities",
     "initial_cost": 0, "monthly_cost": 100,
     "health": 1, "connections": 8, "freedom": 3, "growth": 1, "note_ja": "強力なコミュニティへの帰属", "note_en": "Strong sense of belonging"},

    # ── 5. Growth & Learning ────────────────────────────
    {"category": "learning", "priority": 1,
     "name_ja": "本・電子書籍・Audible", "name_en": "Books / Audible",
     "initial_cost": 0, "monthly_cost": 30,
     "health": 1, "connections": 1, "freedom": 3, "growth": 8, "note_ja": "コスパの良い自己投資", "note_en": "High ROI self-investment"},
    {"category": "learning", "priority": 2,
     "name_ja": "オンライン講座", "name_en": "Online Courses",
     "initial_cost": 0, "monthly_cost": 30,
     "health": 1, "connections": 2, "freedom": 3, "growth": 10, "note_ja": "Udemy/Coursera等", "note_en": "Udemy / Coursera etc."},
    {"category": "learning", "priority": 3,
     "name_ja": "語学学習・アプリ", "name_en": "Language Learning",
     "initial_cost": 0, "monthly_cost": 20,
     "health": 1, "connections": 5, "freedom": 5, "growth": 9, "note_ja": "将来の選択肢を広げる", "note_en": "Expands future options"},
    {"category": "learning", "priority": 4,
     "name_ja": "習い事・対面ワークショップ", "name_en": "Workshops / Classes",
     "initial_cost": 100, "monthly_cost": 100,
     "health": 2, "connections": 7, "freedom": 1, "growth": 8, "note_ja": "スキルと地域のつながり", "note_en": "Skills and local connections"},
    {"category": "learning", "priority": 5,
     "name_ja": "資格取得・専門スクール", "name_en": "Certifications / Schools",
     "initial_cost": 200, "monthly_cost": 50,
     "health": 0, "connections": 3, "freedom": 1, "growth": 9, "note_ja": "キャリアアップに直結", "note_en": "Directly links to career advancement"},
    {"category": "learning", "priority": 6,
     "name_ja": "有料ニュース・専門誌サブスク", "name_en": "Premium News / Journals",
     "initial_cost": 0, "monthly_cost": 40,
     "health": 0, "connections": 2, "freedom": 4, "growth": 6, "note_ja": "質の高い情報収集", "note_en": "High-quality information gathering"},
    {"category": "learning", "priority": 7,
     "name_ja": "プロコーチング・メンタリング", "name_en": "Coaching / Mentoring",
     "initial_cost": 0, "monthly_cost": 200,
     "health": 3, "connections": 5, "freedom": 4, "growth": 10, "note_ja": "客観的視点によるブレークスルー", "note_en": "Breakthrough via objective perspective"},
]