LANG = {
    "ja": {
        "portfolio_btn":            "🔗 ポートフォリオを見る",
        "portfolio_label":          "ポートフォリオ",
        "title":                   "💰 The Life-Value Optimizer",
        "caption":                 "限られた予算で、人生の質を最大化する",
        "step1":                   "Step 1: あなたについて",
        "age":                     "年齢",
        "gender":                  "性別",
        "gender_options":          ["回答しない", "男性", "女性", "その他"],
        "family":                  "家族構成",
        "family_options":          ["一人暮らし", "夫婦", "夫婦＋子供1人", "夫婦＋子供2人", "夫婦＋子供3人", "夫婦＋子供4人", "その他"],
        "monthly_income":          "月収（税引後）（$）",
        "fixed_costs_title":       "固定費（毎月必ず発生するもの）",
        "rent":                    "家賃 / 住宅ローン（$）",
        "utilities":               "電気・ガス・水道（$）",
        "internet":                "インターネット・通信費（$）",
        "groceries":               "食費（基本）（$）",
        "health_insurance_fixed":  "医療保険（$）",
        "other_fixed":             "その他固定費（$）",
        "disposable_income":       "可処分所得（自動計算）",
        "disposable_income_help":  "月収 − 固定費合計。これが最適化の月次予算上限になります",
        "total_budget":            "初期費用の上限（$）",
        "total_budget_help":       "車・家電など一回限りの購入費用の合計上限",
        "step2":                   "Step 2: 目標設定",
        "savings_goal":            "貯蓄目標額（$）",
        "savings_period":          "達成期間",
        "monthly_savings_cap":     "月次目標貯蓄額：${}/月",
        "priority":                "価値観の重み",
        "goal_type":               "目標タイプ",
        "goal_options":            ["今を豊かに生きる", "将来に備える", "健康に長生きする", "自己成長・キャリア", "カスタム"],
        "w_health":                "💪 健康・活力",
        "w_connections":           "🔗 つながり",
        "w_freedom":               "🕐 自由・時間",
        "w_growth":                "🎯 成長・意味",
        "w_savings":               "💰 貯蓄・安心",
        "w_food":                  "🍳 食（本物・体験への志向）",
        "step_lifestyle":          "Step 2.5: 将来の収入見込み",
        "income_increase":         "月次収入増額（$）",
        "income_years":            "実現見込み（年後）",
        "income_reason":           "理由",
        "step3":                   "Step 3: アイテム選択",
        "step3_caption":           "優先度が入力されたアイテムが最適化の候補になります（0=対象外）。費用は実情に合わせて編集可能です。",
        "col_name":                "アイテム名",
        "col_initial":             "初期費用($)",
        "col_monthly":             "月次費用($)",
        "col_health":              "💪",
        "col_connections":         "🔗",
        "col_freedom":             "🕐",
        "col_growth":              "🎯",
        "col_priority":            "優先度",
        "col_mandatory":           "必須",
        "col_note":                "備考",
        "deactivate_all":          "🔴 全非対象",
        "activate_all":            "🟢 リセット",
        "ai_item_placeholder":     "アイテム名を入力（例：ジム、車）",
        "ai_complete_button":      "🤖 AI追加",
        "ai_summary_title":        "🤖 AIサマリー",
        "ai_error_complete":       "AI補完に失敗しました。手動で入力してください。",
        "ai_error_summary":        "サマリーの生成に失敗しました。",
        "risk_toggle":             "現実的なリスクコストを考慮する",
        "risk_title":              "⚠️ リスクコスト予測",
        "risk_caption":            "将来かかる可能性のある費用（保険でカバーされない自己負担分等）。編集可能です。",
        "risk_col_category":       "カテゴリ",
        "risk_col_cost":           "月次コスト($)",
        "risk_effective":          "リスクコスト考慮後の実質月次予算",
        "risk_categories": {
            "medical":    "医療費自己負担（コプレイ等）",
            "housing":    "住居修繕費",
            "car_repair": "車の修理費",
            "education":  "教育費",
            "emergency":  "緊急予備費",
        },
        "run_button":              "🚀 最適化を実行",
        "mandatory_summary_title": "必須・候補アイテムの費用サマリー",
        "must_initial":            "必須：初期費用合計",
        "must_monthly":            "必須：月次費用合計",
        "cand_initial":            "候補：初期費用合計",
        "cand_monthly":            "候補：月次費用合計",
        "validation_initial_over": "❌ 必須アイテムの初期費用合計（${:,}）が上限（${:,}）を超えています",
        "validation_monthly_over": "❌ 必須アイテムの月次費用合計（${:,}）が実質予算（${:,}）を超えています",
        "validation_no_transport": "⚠️ 移動手段カテゴリに候補が1つもありません。優先度を設定してください。",
        "result_ok":               "✅ 最適な組み合わせが見つかりました",
        "result_ng":               "❌ 条件を満たす組み合わせが見つかりませんでした。予算や必須アイテムを見直してください。",
        "total_initial":           "初期費用合計",
        "total_monthly":           "月次費用合計",
        "actual_savings":          "実際の月次貯蓄",
        "savings_rate":            "貯蓄目標達成率",
        "shortfall_warn":          "⚠️ 目標貯蓄額まであと **${}/月** 不足しています。",
        "selected_items":          "選ばれたアイテム",
        "rec_title":               "💡 あなたの満足度を上げる次の一手",
        "rec_within_budget":       "予算内で追加可能",
        "sensitivity_title":       "📊 感度分析",
        "tab_monthly":             "月次予算",
        "tab_initial":             "初期費用上限",
        "chart_value":             "合計バリュー",
        "chart_monthly_x":         "月次予算 ($)",
        "chart_initial_x":         "初期費用上限 ($)",
        "chart_line_title_m":      "月次予算 vs 合計バリュー",
        "chart_line_title_i":      "初期費用上限 vs 合計バリュー",
        "portfolio_btn":           "← ポートフォリオ",
        "reset_btn":               "🔄 リセット",
        "run_opt_btn":             "🚀 最適化を実行",
        "desc":                    "あなたの予算と価値観に基づき、最高のライフスタイルを数理最適化×AIで提案します。",
        # 新UI Step1〜Step4
        "step1_title": "1. 💰 予算と目標の設定",
        "step2_title": "2. 👤 現在のライフスタイル",
        "step3_title": "3. 🧠 価値観と熱量の分析",
        "step4_title": "4. 🤖 AIが提案するあなたのアイテム",
        
        # AI推奨アイテム表示
        "ai_recommended_items_intro": "あなたの生活、価値観、予算に基づき、AIが10個のアイテムを提案しました。不要なものがあれば、削除してください。",
        "ai_recommended_no_items": "推奨アイテムは準備中です。価値観の分析が完了してから表示されます。",
        "ai_item_card_add_btn": "このアイテムを追加",
        "ai_item_card_skip_btn": "スキップ",
        "ai_items_added_count": "選択したアイテム: {count}個",
        
        # 予算入力
        "know_budget_q": "毎月自由に使える予算（可処分所得）は決まっていますか？",
        "yes_calc": "はい",
        "no_calc": "いいえ、計算する",
        "budget_label": "毎月の予算 ($)",
        "calc_expander": "予算の計算",
        "income_label": "手取り月収 ($)",
        "rent_label": "家賃 ($)",
        "fixed_label": "その他固定費 ($)",
        "calc_result": "算出された予算",
        "initial_budget_label": "初期投資に使える貯金 ($)",
        
        # リスク
        "risk_toggle": "⚠️ 現実的なリスクを考慮する",
        
        # 目標
        "goals_subdir": "🎯 目標設定",
        "target_total_label": "目標貯金金額 ($)",
        "period_label": "目標達成までの期間 (年)",
        "alert_savings_impossible": "⚠️ **少し無茶な目標かもしれません**: 目標から計算される月額貯蓄（${int_target:,}）が、今の可処分予算（${int_budget:,}）を超えています。期間か金額の見直しをおすすめします。",
        "alert_savings_high": "⚠️ **かなりストイックな目標です**: 毎月の予算（${int_budget:,}）のうち、{ratio:.0f}%（${int_target:,}）を貯金に回す計算になります。生活費や交際費がかなり圧迫されます。",
        "alert_savings_healthy": "💡 **現実的な目標です**: 毎月の予算（${int_budget:,}）のうち、{ratio:.0f}%（${int_target:,}）を貯金に回す計算になります。",
        
        # ライフスタイル定型(Step2)
        "step2_desc": "あなたに最適な選択肢を絞り込むため、いくつか質問にお答えください。",
        "q_car_necessity": "Q1. 現在のお住まいや生活において、車は必須ですか？",
        "q_own_transport": "Q2. 現在所有している移動手段はありますか？（複数選択可）",
        "own_ebike": "電動自転車",
        "own_moto": "バイク",
        "q_work_style": "Q3. 現在の働き方はどれに一番近いですか？",
        "q_social": "Q4. 人付き合いや、飲み会などの頻度はどのくらいですか？",
        "q_leisure": "Q5. 休日の主な過ごし方（余暇のスタイル）はどれに一番近いですか？",
        "step_food_title": "2b. 🍽️ 食事・交際（飲み）スタイル",
        "step_food_intro": "米国の約2026年時点の物価をベース（Base $400）に推定食費を計算します。係数は内部ロジックのみで使用します。",
        "food_q1": "Q1. 自宅での食事（自炊・テイクアウト）で最も重視するスタイルはどれですか？",
        "food_q2": "Q2. 飲み会・バー・カフェなどの交際支出をどの程度使いますか？",
        "food_q3": "Q3. 交際支出はどんな場が多いですか？",
        "food_q4": "Q4. 次の項目に毎月一定以上の支出がありますか？（複数選択可）",
        "food_home_minimalist": "節約優先。セール品やプライベートブランドを中心に",
        "food_home_standard": "栄養バランスを考え、一般的なスーパーで購入",
        "food_home_health": "オーガニック・無添加・高品質スーパーなど健康投資",
        "food_home_time": "惣菜・カット野菜・冷凍食品など時短重視",
        "food_freq_01": "週に0〜1回",
        "food_freq_23": "週に2〜3回",
        "food_freq_4p": "週に4回以上",
        "food_tone_utility": "効率重視（軽い一杯・短時間の集まり）",
        "food_tone_casual": "バランス（居酒屋・バー・カフェでの交流）",
        "food_tone_experience": "体験重視（特別な店・イベント性の高い会食）",
        "food_opt_alcohol": "アルコール・嗜好品",
        "food_opt_supp": "サプリメント・プロテイン",
        "food_opt_diet": "特殊な食事制限（アレルギー、ベジタリアン など）",
        
        # 価値観デプロイ(Step3：心理テスト)
        "step3_desc": "熟練のライフプランナー兼心理学者として、あなたの深層価値観を抽出するための質問を用意しました。",
        "q_time_deploy": "Q1. もし来週、予期せぬ3日間の休暇と自由な$500が与えられたら？",
        "q_risk_deploy": "Q2. 生活費が1.2倍になりました。『最後まで削りたくない』のは？",
        "q_live_deploy": "Q3. あなたが最も『生きてる実感』を覚える瞬間は？",
        "value_discovery_sub": "🧘 Value Discovery（1〜4）",
        "q_jelly_deploy": "Q4. 完璧な栄養を10秒で補給できる『完全無欠のゼリー』が発明されました。あなたの反応は？",
        "q_jelly_a": "A: 迷わず採用！その分の時間を自分のために使いたい。",
        "q_jelly_b": "B: 平日は採用、週末は拒否。特別な日は食も楽しみたい。",
        "q_jelly_c": "C: 検討の余地なし。常に本物の食事を楽しみたい。",
        "q_jelly_d": "D: むしろ、そのゼリーの分を節約して他にお金を使いたい。",
        "freetext_q5_intro": "Q5. 最後に、あなたの人生で譲れないこだわり、理想の生活、追加したいことなど自由に教えてください。",
        "step3_freetext_desc": "あなたの人生で譲れないこだわり、理想の生活、追加したいことなど自由に教えてください。",
        "freetext_label": "自由記述 (人生の優先順位)",
        "freetext_placeholder": "例：毎年家族で海外旅行に行きたい。親の介護の時間も確保したい。その他は柔軟に対応できます。",
        "analyzing": "プロファイリング中...",
        "analysis_success": "AIがあなたの深層価値観を推論しました！下のスライダーで最終調整してください。",
        "analysis_fail": "AI分析に失敗しました。手動で設定してください。",
        "analysis_fallback": "AIへの接続に失敗したか、応答を解釈できませんでした。これまでの質問・自由記述から重みを推定してスライダーに反映しました。必要に応じて手で調整してください。",
        "analysis_manual_mode": "AIを使わず、これまでの質問と自由記述から重みを推定して反映しました。",
        "use_ai_for_values": "🤖 AIを使って価値観を反映",
        "reflect_to_slider_btn": "✨ 価値観をスライダーに反映",
        "use_ai_for_optimize": "🤖 AIを使って最適化結果サマリーを作成",
        "ai_summary_off": "AIサマリーはOFFです。数理最適化の結果のみ表示しています。",
        "w_subdir": "⚖️ 価値観の重み (1〜10)",
        
        # アイテム修正(Step4)
        "item_review_expander": "デフォルトカテゴリの一覧と編集",
        "item_review_info": "不要なアイテムは優先度を0に、所有済みアイテムは初期費用を0に調整してください。カスタムアイテムの追加も可能です。",
        "item_list_subheader": "カテゴリ別の一覧と編集",
        "mandatory_label": "必須",
        "col_ic": "初期コスト",
        "col_mc": "月次コスト",
        "opt_no_candidates": "候補アイテムがありません。Step 4 で少なくとも1件、優先度を1以上にするか必須にしてください。",
        "opt_best_effort_zero_food": "ベストエフォート: 食費の可変枠（Stage1/2）を0にして再計算しました。",
        "opt_best_effort_transport": "ベストエフォート: 「移動手段を1つ選ぶ」制約を外して再計算しました（移動ゼロも許容）。",
        "opt_spinner": "数理最適化を実行しています…",
        "sidebar_title": "設定",
        "sidebar_language": "言語",
        "step89_title": "5. 📊 サマリーと最適化",
        "step89_intro": "設定は完了しています。入力した予算と価値観に基づき、最適なライフスタイルの組み合わせを計算します。",
        "section_budget": "💵 月次予算と初期投資",
        "section_profile": "👪 世帯とリスクプロフィール",
        "calc_fixed_subheading": "固定費の内訳",
        "lbl_rent_util": "家賃＋光熱費（$）",
        "lbl_insurance": "保険料（$）",
        "lbl_telecom": "通信費（$）",
        "lbl_debt_repayment": "ローン・負債の月額返済（$）",
        "lbl_other_fixed": "その他固定費（$）",
        "risk_household_caption": "食費推定と世帯規模の計算に使います。",
        "lbl_age": "本人の年齢",
        "lbl_adults": "同居・大人",
        "lbl_children": "同居・子ども",
        "lbl_infants": "同居・乳幼児",
        "family_summary_fmt": "大人{adults}・子供{children}・乳幼児{infants}",
        "own_car": "車",
        "own_bike": "自転車",
        "own_none": "なし",
        "lifestyle_q1_options": [
            "A: 車がないと生活できない（必須）",
            "B: できれば車が欲しいが、なくてもなんとかなる",
            "C: 公共交通機関や自転車で十分（不要）",
        ],
        "lifestyle_q_work_options": [
            "A: フルリモート（ほぼ在宅）",
            "B: ハイブリッド（週の半分くらい出社）",
            "C: フル出社・現場仕事",
        ],
        "lifestyle_q_social_options": [
            "A: 頻繁に行く（お酒も場も好き）",
            "B: たまに行く程度",
            "C: 一人の時間を優先したい",
        ],
        "lifestyle_q_leisure_options": [
            "A: インドア・リラックス派",
            "B: アクティブ・アウトドア派",
            "C: お出かけ・イベント派",
        ],
        "step3_part1_sub": "🧘 Value Discovery（パート1：Q1〜Q3）",
        "step3_part2_sub": "🧘 Value Discovery（パート2：Q4〜Q5）",
        "values_q_time_options": [
            "A: 未経験のアクティビティや学習に没頭する",
            "B: 親しい友人や家族と豊かな時間を過ごす",
            "C: 身体を休め、健康ルーティンを整える",
            "D: 将来のために全額を貯金し、家で過ごす",
        ],
        "values_q_risk_options": [
            "A: スキルアップのための書籍や講座代",
            "B: 趣味や移動にかかる費用",
            "C: 健康維持のためのジムや食材代",
            "D: 将来の備えとしての積立",
        ],
        "values_q_live_options": [
            "A: 誰にも縛られず、自分のペースで動けているとき",
            "B: 新しいことを学び、能力が向上していると感じるとき",
            "C: 誰かの役に立ち、感謝や交流があるとき",
            "D: 身体が軽く、メンタルが安定しているとき",
        ],
        "add_custom_item_title": "➕ カスタムアイテムを追加",
        "form_category": "カテゴリ",
        "form_item_name": "アイテム名",
        "form_priority": "優先度",
        "form_initial": "初期費用（$）",
        "form_monthly": "月額費用（$）",
        "form_health": "健康",
        "form_connections": "つながり",
        "form_freedom": "自由",
        "form_growth": "成長",
        "form_submit_add": "追加する",
        "warn_item_name_required": "アイテム名を入力してください。",
        "err_category_resolve": "カテゴリの解決に失敗しました。",
        "success_item_added": "アイテムを追加しました。",
        "success_item_removed": "アイテムを削除しました。",
        "item_slider_caption_mandatory": "必須",
        "item_slider_suffix": "（優先度0＝対象外）",
        "lbl_mc": "月額（$）",
        "lbl_ic": "初期（$）",
        "opt_fail": "最適化に失敗しました。予算や必須アイテム、候補の優先度を見直してください。",
        "opt_success": "最適化が完了しました。",
        "best_effort_mandatory_ok": "制約のなかで、可能な限りよいプランを組み立てました。",
        "best_effort_mandatory_warn": "必須指定の一部が予算内に収まらなかったため、ベストエフォートで再計算しました（必須{relaxed}件のうち、反映できず{missed}件）。",
        "missed_mandatory_heading": "反映できなかった必須アイテム",
        "sel_items": "選択されたアイテム",
        "ai_dashboard": "💡 AIライフコーチ・サマリー",
        "theme": "テーマ",
        "analysis": "分析",
        "blind_spot": "死角・リスク",
        "next_action": "次のアクション",
        "none": "なし",
        "dash_exec_title": "📌 実行ダッシュボード",
        "dash_section_overview_title": "📊 予算の配分サマリー",
        "dash_food_floor_caption": "食費のミニマム（Minimalist）${floor:,}/月を控除したうえで、残りの可処分予算を最適化しています。",
        "dash_metric_monthly_pool": "月次予算",
        "dash_metric_monthly_pool_help": "消費 {spend} + 貯蓄 {save} = {total}",
        "dash_metric_initial_cap": "初期費用の上限",
        "dash_metric_initial_used": "消費 {used}",
        "dash_metric_monthly_savings": "月次貯蓄（配分内）",
        "dash_metric_monthly_savings_help": "予算のうち貯蓄に回した額です。",
        "dash_metric_initial_left": "初期費用の残り",
        "dash_metric_savings_rate": "貯蓄目標に対する達成率",
        "dash_rounding_note": "月次配分の合計と上限に数ドル差がある場合は、整数丸めの影響です。",
        "dash_food_floor_metric": "食費・ミニマム（固定）",
        "dash_food_stage1_metric": "食費・Stage1（希望水準まで）",
        "dash_food_stage1_delta": "上限 {cap_str} に対し {pct:.0%}",
        "dash_food_stage2_metric": "食費・Stage2（上振れ枠）",
        "dash_food_stage2_delta": "上限 {cap_str} に対し {pct:.0%}",
        "dash_food_total_caption": "食費合計（固定＋Stage1＋Stage2）: ${total:,}/月",
        "dash_section_2_title": "📈 カテゴリ別の月次・初期の内訳",
        "dash_chart_monthly_mix": "月次の構成比（%）",
        "dash_chart_initial_mix": "初期費用の構成比（%）",
        "dash_col_category": "カテゴリ",
        "dash_col_monthly": "月額（$）",
        "dash_col_monthly_pct": "月額（%）",
        "dash_col_initial": "初期（$）",
        "dash_col_initial_pct": "初期（%）",
        "dash_cat_savings": "貯蓄",
        "dash_cat_food": "食費",
        "dash_section_savings_title": "💰 貯蓄目標の見通し",
        "dash_metric_target_total": "目標貯蓄総額",
        "dash_metric_projected_total": "見込み貯蓄総額",
        "dash_metric_achievement": "目標に対する達成率",
        "dash_metric_remaining_goal": "目標までの不足額",
        "dash_caption_goal_progress": "{years}年での目標進捗: {pct:.0%}",
        "dash_caption_surplus": "目標を上回る見込み: ${amt:,.0f}",
        "dash_caption_target_source": "目標総額は入力値を使用しています（{years}年）。",
        "dash_chart_bar_goal": "貯蓄目標",
        "dash_chart_achieved": "達成分",
        "dash_chart_remaining": "残り",
        "dash_chart_over": "超過分",
        "dash_gap_caption": "目標までのギャップ: ${gap:,.0f}",
        "dash_section_values_title": "❤️ 選択アイテムによる価値観の充足",
        "dash_col_value": "価値観",
        "dash_col_score": "スコア",
        "dash_col_fulfillment": "充足率（%）",
        "dash_col_weighted": "重み反映値",
        "dash_value_match": "価値観マッチ度",
        "dash_value_match_help": "重みの配分と実現の配分の距離から算出（1 − 0.5×L1）。高いほど一致しています。",
        "dash_values_chart_caption": "選択アイテムごとの価値観充足率",
        "dash_no_items_in_cat": "このカテゴリに選択されたアイテムはありません。",
        "dash_item_summary": "{n}件 · 初期 ${ic:,} · 月額 ${mc:,}",
        "dash_item_initial": "初期",
        "dash_item_monthly": "月額",
        "val_axis_food": "食",
        "food_advice": "食費の分析",
        "savings_advice": "貯蓄の分析",
        
        # Passion Text Input (新規Step 0.5)
        "passion_title": "✨ あなたのことを教えてください",
        "passion_intro": "自由に、あなたの人生・興味・仕事・現在地について語ってください。その文章から、あなたにぴったり合うアイテムと価値観を AI が読み取ります。",
        "passion_label": "あなたについて教えてください",
        "passion_placeholder": "例）ハワイに住んでいる大学生で、車は持っています。週末は海に行くのが好きで、友人との交流も大切にしています。",
        "extract_profile_btn": "🔍 あなたのプロフィールを分析",
        "passion_analysis_success": "✅ プロフィール抽出完了！",
    },
    "en": {
        "portfolio_btn":            "🔗 View Portfolio",
        "portfolio_label":          "Portfolio",
        "title":                   "💰 The Life-Value Optimizer",
        "caption":                 "Maximize your life quality within a limited budget",
        "step1":                   "Step 1: About You",
        "age":                     "Age",
        "gender":                  "Gender",
        "gender_options":          ["Prefer not to say", "Male", "Female", "Other"],
        "family":                  "Household",
        "family_options":          ["Single", "Couple", "Couple + 1 Kid", "Couple + 2 Kids", "Couple + 3 Kids", "Couple + 4 Kids", "Other"],
        "monthly_income":          "Monthly Income (after tax) ($)",
        "fixed_costs_title":       "Fixed Costs (monthly necessities)",
        "rent":                    "Rent / Mortgage ($)",
        "utilities":               "Utilities (Electric/Gas/Water) ($)",
        "internet":                "Internet & Phone ($)",
        "groceries":               "Groceries (basic) ($)",
        "health_insurance_fixed":  "Health Insurance ($)",
        "other_fixed":             "Other Fixed Costs ($)",
        "disposable_income":       "Disposable Income (auto-calculated)",
        "disposable_income_help":  "Income − Fixed costs. This becomes your monthly budget for optimization.",
        "total_budget":            "Initial Cost Limit ($)",
        "total_budget_help":       "Total limit for one-time purchases (car, appliances, etc.)",
        "step2":                   "Step 2: Goal Setting",
        "savings_goal":            "Savings Goal ($)",
        "savings_period":          "Target Period",
        "monthly_savings_cap":     "Monthly savings target: ${}/month",
        "priority":                "Value Weights",
        "goal_type":               "Goal Type",
        "goal_options":            ["Live Well Now", "Build for the Future", "Health & Longevity", "Growth & Career", "Custom"],
        "w_health":                "💪 Health & Vitality",
        "w_connections":           "🔗 Relationships",
        "w_freedom":               "🕐 Freedom & Time",
        "w_growth":                "🎯 Growth & Purpose",
        "w_savings":               "💰 Security & Savings",
        "w_food":                  "🍳 Food (experience & authenticity)",
        "step_lifestyle":          "Step 2.5: Future Income Projection",
        "income_increase":         "Monthly Income Increase ($)",
        "income_years":            "Expected in (years)",
        "income_reason":           "Reason",
        "step3":                   "Step 3: Item Selection",
        "step3_caption":           "Items with a priority number become optimization candidates (0 = excluded). You can edit costs to match your situation.",
        "col_name":                "Item",
        "col_initial":             "Initial($)",
        "col_monthly":             "Monthly($)",
        "col_health":              "💪",
        "col_connections":         "🔗",
        "col_freedom":             "🕐",
        "col_growth":              "🎯",
        "col_priority":            "Priority",
        "col_mandatory":           "Must",
        "col_note":                "Note",
        "deactivate_all":          "🔴 All Off",
        "activate_all":            "🟢 Reset",
        "ai_item_placeholder":     "Enter item name (e.g. Gym, Car)",
        "ai_complete_button":      "🤖 AI Add",
        "ai_summary_title":        "🤖 AI Summary",
        "ai_error_complete":       "AI completion failed. Please fill in manually.",
        "ai_error_summary":        "Failed to generate summary.",
        "risk_toggle":             "Consider realistic risk costs",
        "risk_title":              "⚠️ Risk Cost Estimate",
        "risk_caption":            "Estimated out-of-pocket costs not covered by insurance. You can edit these values.",
        "risk_col_category":       "Category",
        "risk_col_cost":           "Monthly Cost($)",
        "risk_effective":          "Effective monthly budget after risk costs",
        "risk_categories": {
            "medical":    "Medical Out-of-Pocket (copay etc.)",
            "housing":    "Housing Repair",
            "car_repair": "Car Repair",
            "education":  "Education",
            "emergency":  "Emergency Fund",
        },
        "run_button":              "🚀 Optimize",
        "mandatory_summary_title": "Mandatory & Candidate Cost Summary",
        "must_initial":            "Must: Total Initial",
        "must_monthly":            "Must: Total Monthly",
        "cand_initial":            "Candidates: Total Initial",
        "cand_monthly":            "Candidates: Total Monthly",
        "validation_initial_over": "❌ Mandatory items total initial cost (${:,}) exceeds limit (${:,})",
        "validation_monthly_over": "❌ Mandatory items total monthly cost (${:,}) exceeds effective budget (${:,})",
        "validation_no_transport": "⚠️ No transport candidates selected. Please set a priority for at least one.",
        "result_ok":               "✅ Optimal combination found",
        "result_ng":               "❌ No valid combination found. Please review your budget or mandatory items.",
        "total_initial":           "Total Initial Cost",
        "total_monthly":           "Total Monthly Cost",
        "actual_savings":          "Actual Monthly Savings",
        "savings_rate":            "Savings Goal Rate",
        "shortfall_warn":          "⚠️ **${}/month** short of your savings goal.",
        "selected_items":          "Selected Items",
        "rec_title":               "💡 Next steps to boost your satisfaction",
        "rec_within_budget":       "Can be added within budget",
        "sensitivity_title":       "📊 Sensitivity Analysis",
        "tab_monthly":             "Monthly Budget",
        "tab_initial":             "Initial Cost Limit",
        "chart_value":             "Total Value",
        "chart_monthly_x":         "Monthly Budget ($)",
        "chart_initial_x":         "Initial Cost Limit ($)",
        "chart_line_title_m":      "Monthly Budget vs Total Value",
        "chart_line_title_i":      "Initial Cost Limit vs Total Value",
        "portfolio_btn":           "Portfolio",
        "reset_btn":               "🔄 Reset",
        "run_opt_btn":             "🚀 Run Optimization",
        "desc":                    "Proposing the optimal lifestyle based on your budget and values using mathematical optimization & AI.",
        "step1_title": "1. 💰 Budget & Goals",
        "step2_title": "2. 👤 Current Lifestyle",
        "step3_title": "3. 🧠 Values & Passion",
        "step4_title": "4. 🤖 AI-Recommended Items",
        
        # AI推奨アイテム表示
        "ai_recommended_items_intro": "Based on your lifestyle, values, and budget, AI has proposed 10 personalized items. If you don't want something, please delete it.",
        "ai_recommended_no_items": "Recommended items are being prepared. They will appear once your values have been analyzed.",
        "ai_item_card_add_btn": "Add This Item",
        "ai_item_card_skip_btn": "Skip",
        "ai_items_added_count": "Selected items: {count}",
        
        "know_budget_q": "Do you know your monthly disposable budget?",
        "yes_calc": "Yes",
        "no_calc": "No, calculate it",
        "budget_label": "Monthly Budget ($)",
        "calc_expander": "Calculate Budget",
        "income_label": "Monthly Net Income ($)",
        "rent_label": "Rent ($)",
        "fixed_label": "Other Fixed Costs ($)",
        "calc_result": "Calculated Budget",
        "initial_budget_label": "Initial Budget ($)",
        "risk_toggle": "⚠️ Consider realistic risks",
        "goals_subdir": "🎯 Goals",
        "target_total_label": "Target Savings Amount ($)",
        "period_label": "Years to achieve goal",
        "step2_desc": "Answer a few questions to help us tailor the options for you.",
        "q_car_necessity": "Q1. Is a car essential for your lifestyle?",
        "q_own_transport": "Q2. What transport do you currently own? (Multiple allowed)",
        "own_ebike": "E-Bike",
        "own_moto": "Motorcycle",
        "q_work_style": "Q3. What is your current work style?",
        "q_social": "Q4. How often do you socialize or go out for drinks?",
        "q_leisure": "Q5. What is your primary leisure style?",
        "step_food_title": "2b. 🍽️ Food & social-drinks style",
        "step_food_intro": "Estimated food spending uses U.S. ~2026 prices as a base (Base $400). Internal coefficients are for the model only.",
        "food_q1": "Q1. Which style do you prioritize most for meals at home (cooking and takeout)?",
        "food_q2": "Q2. How much do you spend on social outings (bars, drinks, cafes)?",
        "food_q3": "Q3. What kinds of venues are most common for your social spending?",
        "food_q4": "Q4. Do you spend a meaningful amount each month on any of the following? (Multiple selections allowed)",
        "food_home_minimalist": "Budget-first, sales and store brands",
        "food_home_standard": "Balanced nutrition, typical grocery stores",
        "food_home_health": "Organic, additive-free, premium grocery quality",
        "food_home_time": "Deli meals, pre-cut produce, frozen convenience",
        "food_freq_01": "0–1 times per week",
        "food_freq_23": "2–3 times per week",
        "food_freq_4p": "4+ times per week",
        "food_tone_utility": "Quick/low-cost meetups and short drinks",
        "food_tone_casual": "Bars, izakaya-style places, cafes with friends",
        "food_tone_experience": "Premium venues and event-like dining/drinks",
        "food_opt_alcohol": "Alcohol and similar",
        "food_opt_supp": "Supplements and protein",
        "food_opt_diet": "Special diets (allergies, vegetarian, keto, etc.)",
        "step3_desc": "We prepare questions to extract your deep values.",
        "q_time_deploy": "Q1. Surprise 3-day vacation and $500. What would you do?",
        "q_risk_deploy": "Q2. Cost of living 1.2x. What is the last thing you cut?",
        "q_live_deploy": "Q3. When do you feel most 'alive'?",
        "value_discovery_sub": "🧘 Value Discovery (1-4)",
        "q_jelly_deploy": "Q4. A perfect-nutrition jelly gives you everything you need in 10 seconds. How do you react?",
        "q_jelly_a": "A: I'd adopt it—I'd use that time for myself.",
        "q_jelly_b": "B: Weekdays yes, weekends no—I still want real meals on special days.",
        "q_jelly_c": "C: Not interested—I always want to enjoy real food.",
        "q_jelly_d": "D: I'd rather save that money and spend it on other things.",
        "freetext_q5_intro": "Q5. Finally, share your life non-negotiables, ideal lifestyle additions, and priorities.",
        "step3_freetext_desc": "Share your life non-negotiables, ideal lifestyle additions, and priorities.",
        "freetext_label": "Free Text (Life Priorities)",
        "freetext_placeholder": "e.g., I want to travel internationally with family once a year. Caring for aging parents is non-negotiable. Everything else I can be flexible about.",
        "analyzing": "Analyzing...",
        "analysis_success": "AI has inferred your deep values! Fine-tune them below.",
        "analysis_fail": "AI analysis failed. Please set manually.",
        "analysis_fallback": "Could not reach the AI or parse its reply. We estimated weights from your answers and free text and applied them to the sliders. Adjust manually if needed.",
        "analysis_manual_mode": "Applied estimated weights from your answers and free text without using AI.",
        "use_ai_for_values": "🤖 Use AI for value reflection",
        "reflect_to_slider_btn": "✨ Reflect values to sliders",
        "use_ai_for_optimize": "🤖 Use AI to generate optimization summary",
        "ai_summary_off": "AI summary is OFF. Showing optimization results only.",
        "w_subdir": "⚖️ Value Weights (1-10)",
        "item_review_expander": "Default Category Items & Editing",
        "item_review_info": "Adjust priorities or costs for any items. You can also add custom items here if needed.",
        "item_list_subheader": "Browse and edit by category",
        "mandatory_label": "Mandatory",
        "col_ic": "Initial Cost",
        "col_mc": "Monthly Cost",
        "opt_no_candidates": "No candidate items. In Step 4, set priority ≥ 1 for at least one item, or mark one as mandatory.",
        "opt_best_effort_zero_food": "Best effort: re-ran with food variable budget (Stage1/2) set to $0.",
        "opt_best_effort_transport": "Best effort: re-ran without the “pick exactly one transport mode” rule (zero transport allowed).",
        "opt_spinner": "Running optimization…",
        "sidebar_title": "Settings",
        "sidebar_language": "Language",
        "step89_title": "5. 📊 Summary & optimization",
        "step89_intro": "Setup is complete. We will compute the best lifestyle mix from your budget and values.",
        "section_budget": "💵 Monthly budget & initial fund",
        "section_profile": "👪 Household & risk profile",
        "calc_fixed_subheading": "Fixed-cost breakdown",
        "lbl_rent_util": "Rent + utilities ($)",
        "lbl_insurance": "Insurance ($)",
        "lbl_telecom": "Phone & internet ($)",
        "lbl_debt_repayment": "Loan / Debt repayment ($)",
        "lbl_other_fixed": "Other fixed costs ($)",
        "risk_household_caption": "Used for food-cost estimation and household scaling.",
        "lbl_age": "Your age",
        "lbl_adults": "Adults in household",
        "lbl_children": "Children",
        "lbl_infants": "Infants / toddlers",
        "family_summary_fmt": "Adults: {adults}, children: {children}, infants: {infants}",
        "own_car": "Car",
        "own_bike": "Bicycle",
        "own_none": "None",
        "lifestyle_q1_options": [
            "A: Car is essential",
            "B: Nice to have, but manageable without",
            "C: Not needed (transit or bike is enough)",
        ],
        "lifestyle_q_work_options": [
            "A: Fully remote (mostly home)",
            "B: Hybrid (~half the week on-site)",
            "C: Full office / on-site work",
        ],
        "lifestyle_q_social_options": [
            "A: Frequent (enjoy drinks and going out)",
            "B: Occasionally",
            "C: Prefer solo time",
        ],
        "lifestyle_q_leisure_options": [
            "A: Indoor / relax",
            "B: Active / outdoor",
            "C: Outings / events",
        ],
        "step3_part1_sub": "🧘 Value Discovery — Part 1 (Q1–Q3)",
        "step3_part2_sub": "🧘 Value Discovery — Part 2 (Q4–Q5)",
        "values_q_time_options": [
            "A: Dive into a new activity or learning",
            "B: Spend rich time with close friends or family",
            "C: Rest and lock in a health routine",
            "D: Save it all for the future and stay home",
        ],
        "values_q_risk_options": [
            "A: Books and courses to skill up",
            "B: Hobbies and transportation",
            "C: Gym and healthy food",
            "D: Savings and reserves",
        ],
        "values_q_live_options": [
            "A: Moving at my own pace, not tied down",
            "B: Learning something new and feeling growth",
            "C: Helping others and feeling connection",
            "D: Feeling light in body and stable in mind",
        ],
        "add_custom_item_title": "➕ Add a custom item",
        "form_category": "Category",
        "form_item_name": "Item name",
        "form_priority": "Priority",
        "form_initial": "Initial cost ($)",
        "form_monthly": "Monthly cost ($)",
        "form_health": "Health",
        "form_connections": "Connections",
        "form_freedom": "Freedom",
        "form_growth": "Growth",
        "form_submit_add": "Add item",
        "warn_item_name_required": "Please enter an item name.",
        "err_category_resolve": "Could not resolve category.",
        "success_item_added": "Item added.",
        "success_item_removed": "Item removed.",
        "item_slider_caption_mandatory": "Mandatory",
        "item_slider_suffix": "(priority 0 = excluded)",
        "lbl_mc": "Monthly ($)",
        "lbl_ic": "Initial ($)",
        "opt_fail": "Optimization failed. Review budget, mandatory items, and candidate priorities.",
        "opt_success": "Optimization completed.",
        "best_effort_mandatory_ok": "Built the best feasible plan within your constraints.",
        "best_effort_mandatory_warn": "Some mandatory items did not fit the budget; best-effort rerun applied ({missed} of {relaxed} mandatory items not reflected).",
        "missed_mandatory_heading": "Mandatory items not reflected",
        "sel_items": "Selected items",
        "ai_dashboard": "💡 AI life-coach summary",
        "theme": "Theme",
        "analysis": "Analysis",
        "blind_spot": "Blind spots & risks",
        "next_action": "Next action",
        "none": "None",
        "dash_exec_title": "📌 Execution dashboard",
        "dash_section_overview_title": "📊 Budget allocation overview",
        "dash_food_floor_caption": "Disposable budget for optimization is after subtracting the Minimalist food floor (${floor:,}/mo).",
        "dash_metric_monthly_pool": "Monthly budget",
        "dash_metric_monthly_pool_help": "Spend {spend} + Save {save} = {total}",
        "dash_metric_initial_cap": "Initial cost limit",
        "dash_metric_initial_used": "Consumed {used}",
        "dash_metric_monthly_savings": "Monthly savings (allocated)",
        "dash_metric_monthly_savings_help": "This is savings within your budget.",
        "dash_metric_initial_left": "Initial budget remaining",
        "dash_metric_savings_rate": "Savings goal attainment",
        "dash_rounding_note": "Small mismatch vs. the cap is usually integer rounding.",
        "dash_food_floor_metric": "Food floor (fixed)",
        "dash_food_stage1_metric": "Food Stage1 (to survey target)",
        "dash_food_stage1_delta": "{pct:.0%} of {cap_str} cap",
        "dash_food_stage2_metric": "Food Stage2 (upgrade band)",
        "dash_food_stage2_delta": "{pct:.0%} of {cap_str} cap",
        "dash_food_total_caption": "Total food (floor + Stage1 + Stage2): ${total:,}/mo",
        "dash_section_2_title": "📈 Spend mix by category",
        "dash_chart_monthly_mix": "Monthly mix (%)",
        "dash_chart_initial_mix": "Initial mix (%)",
        "dash_col_category": "Category",
        "dash_col_monthly": "Monthly ($)",
        "dash_col_monthly_pct": "Monthly (%)",
        "dash_col_initial": "Initial ($)",
        "dash_col_initial_pct": "Initial (%)",
        "dash_cat_savings": "Savings",
        "dash_cat_food": "Food",
        "dash_section_savings_title": "💰 Savings outlook",
        "dash_metric_target_total": "Target savings (total)",
        "dash_metric_projected_total": "Projected savings (total)",
        "dash_metric_achievement": "Progress toward target",
        "dash_metric_remaining_goal": "Remaining to target",
        "dash_caption_goal_progress": "Progress over {years} years: {pct:.0%}",
        "dash_caption_surplus": "Projected above target: ${amt:,.0f}",
        "dash_caption_target_source": "Target total uses your input ({years} years).",
        "dash_chart_bar_goal": "Savings goal",
        "dash_chart_achieved": "Achieved",
        "dash_chart_remaining": "Remaining",
        "dash_chart_over": "Above target",
        "dash_gap_caption": "Gap to goal: ${gap:,.0f}",
        "dash_section_values_title": "❤️ Value fulfillment from selected items",
        "dash_col_value": "Value",
        "dash_col_score": "Score",
        "dash_col_fulfillment": "Fulfillment (%)",
        "dash_col_weighted": "Weighted score",
        "dash_value_match": "Value match score",
        "dash_value_match_help": "From distance between weight share and realized share (1 − 0.5×L1). Higher is closer alignment.",
        "dash_values_chart_caption": "Fulfillment rate by value axis",
        "dash_no_items_in_cat": "No selected items in this category.",
        "dash_item_summary": "{n} item(s) · Initial ${ic:,} · Monthly ${mc:,}",
        "dash_item_initial": "Initial",
        "dash_item_monthly": "Monthly",
        "val_axis_food": "Food",
        "food_advice": "Food investment",
        "savings_advice": "Savings analysis",
        
        # Passion Text Input (new Step 0.5)
        "passion_title": "✨ Tell us about yourself",
        "passion_intro": "Share freely about your life, interests, work, location, and anything important to you. We will use AI to read your story and find items and values that are perfect for you.",
        "passion_label": "Tell us about yourself",
        "passion_placeholder": "e.g.) I'm a student in Hawaii with a car. I love going to the beach on weekends and value time with friends.",
        "extract_profile_btn": "🔍 Analyze your profile",
        "passion_analysis_success": "✅ Profile extracted!",
    }
}

PRESETS = {
    "ja": {
        "今を豊かに生きる":   {"health": 4, "connections": 7, "freedom": 7, "growth": 4, "savings": 2},
        "将来に備える":       {"health": 3, "connections": 2, "freedom": 3, "growth": 5, "savings": 9},
        "健康に長生きする":   {"health": 9, "connections": 5, "freedom": 4, "growth": 4, "savings": 4},
        "自己成長・キャリア": {"health": 4, "connections": 5, "freedom": 3, "growth": 9, "savings": 5},
        "カスタム":           {"health": 5, "connections": 5, "freedom": 5, "growth": 5, "savings": 5},
    },
    "en": {
        "Live Well Now":        {"health": 4, "connections": 7, "freedom": 7, "growth": 4, "savings": 2},
        "Build for the Future": {"health": 3, "connections": 2, "freedom": 3, "growth": 5, "savings": 9},
        "Health & Longevity":   {"health": 9, "connections": 5, "freedom": 4, "growth": 4, "savings": 4},
        "Growth & Career":      {"health": 4, "connections": 5, "freedom": 3, "growth": 9, "savings": 5},
        "Custom":               {"health": 5, "connections": 5, "freedom": 5, "growth": 5, "savings": 5},
    }
}