LANG = {
    "ja": {
        "portfolio_btn":            "🔗 ポートフォリオを見る",
        "portfolio_label":          "ポートフォリオ",
        "title":                   "💰 The Life-Value Optimizer",
        "caption":                 "限られた予算で、人生の質を最大化する",
        "step1":                   "Step 1: あなたについて",
        "age":                     "年齢",
        "gender":                  "性別",
        "gender_options":          ["回答しない", "男性", "女性", "その他"],
        "family":                  "家族構成",
        "family_options":          ["一人暮らし", "夫婦", "夫婦＋子供1人", "夫婦＋子供2人", "夫婦＋子供3人", "夫婦＋子供4人", "その他"],
        "monthly_income":          "月収（税引後）（$）",
        "fixed_costs_title":       "固定費（毎月必ず発生するもの）",
        "rent":                    "家賃 / 住宅ローン（$）",
        "utilities":               "電気・ガス・水道（$）",
        "internet":                "インターネット・通信費（$）",
        "groceries":               "食費（基本）（$）",
        "health_insurance_fixed":  "医療保険（$）",
        "other_fixed":             "その他固定費（$）",
        "disposable_income":       "可処分所得（自動計算）",
        "disposable_income_help":  "月収 − 固定費合計。これが最適化の月次予算上限になります",
        "total_budget":            "初期費用の上限（$）",
        "total_budget_help":       "車・家電など一回限りの購入費用の合計上限",
        "step2":                   "Step 2: 目標設定",
        "savings_goal":            "貯蓄目標額（$）",
        "savings_period":          "達成期間",
        "monthly_savings_cap":     "月次目標貯蓄額：${}/月",
        "priority":                "価値観の重み",
        "goal_type":               "目標タイプ",
        "goal_options":            ["今を豊かに生きる", "将来に備える", "健康に長生きする", "自己成長・キャリア", "カスタム"],
        "w_health":                "💪 健康・活力",
        "w_connections":           "🔗 つながり",
        "w_freedom":               "🕐 自由・時間",
        "w_growth":                "🎯 成長・意味",
        "w_savings":               "💰 貯蓄・安心",
        "w_food":                  "🍳 食（本物・体験への志向）",
        "step_lifestyle":          "Step 2.5: 将来の収入見込み",
        "income_increase":         "月次収入増額（$）",
        "income_years":            "実現見込み（年後）",
        "income_reason":           "理由",
        "step3":                   "Step 3: アイテム選択",
        "step3_caption":           "優先度が入力されたアイテムが最適化の候補になります（0=対象外）。費用は実情に合わせて編集可能です。",
        "col_name":                "アイテム名",
        "col_initial":             "初期費用($)",
        "col_monthly":             "月次費用($)",
        "col_health":              "💪",
        "col_connections":         "🔗",
        "col_freedom":             "🕐",
        "col_growth":              "🎯",
        "col_priority":            "優先度",
        "col_mandatory":           "必須",
        "col_note":                "備考",
        "deactivate_all":          "🔴 全非対象",
        "activate_all":            "🟢 リセット",
        "ai_item_placeholder":     "アイテム名を入力（例：ジム、車）",
        "ai_complete_button":      "🤖 AI追加",
        "ai_summary_title":        "🤖 AIサマリー",
        "ai_error_complete":       "AI補完に失敗しました。手動で入力してください。",
        "ai_error_summary":        "サマリーの生成に失敗しました。",
        "risk_toggle":             "現実的なリスクコストを考慮する",
        "risk_title":              "⚠️ リスクコスト予測",
        "risk_caption":            "将来かかる可能性のある費用（保険でカバーされない自己負担分等）。編集可能です。",
        "risk_col_category":       "カテゴリ",
        "risk_col_cost":           "月次コスト($)",
        "risk_effective":          "リスクコスト考慮後の実質月次予算",
        "risk_categories": {
            "medical":    "医療費自己負担（コプレイ等）",
            "housing":    "住居修繕費",
            "car_repair": "車の修理費",
            "education":  "教育費",
            "emergency":  "緊急予備費",
        },
        "run_button":              "🚀 最適化を実行",
        "mandatory_summary_title": "必須・候補アイテムの費用サマリー",
        "must_initial":            "必須：初期費用合計",
        "must_monthly":            "必須：月次費用合計",
        "cand_initial":            "候補：初期費用合計",
        "cand_monthly":            "候補：月次費用合計",
        "validation_initial_over": "❌ 必須アイテムの初期費用合計（${:,}）が上限（${:,}）を超えています",
        "validation_monthly_over": "❌ 必須アイテムの月次費用合計（${:,}）が実質予算（${:,}）を超えています",
        "validation_no_transport": "⚠️ 移動手段カテゴリに候補が1つもありません。優先度を設定してください。",
        "result_ok":               "✅ 最適な組み合わせが見つかりました",
        "result_ng":               "❌ 条件を満たす組み合わせが見つかりませんでした。予算や必須アイテムを見直してください。",
        "total_initial":           "初期費用合計",
        "total_monthly":           "月次費用合計",
        "actual_savings":          "実際の月次貯蓄",
        "savings_rate":            "貯蓄目標達成率",
        "shortfall_warn":          "⚠️ 目標貯蓄額まであと **${}/月** 不足しています。",
        "selected_items":          "選ばれたアイテム",
        "rec_title":               "💡 あなたの満足度を上げる次の一手",
        "rec_within_budget":       "予算内で追加可能",
        "sensitivity_title":       "📊 感度分析",
        "tab_monthly":             "月次予算",
        "tab_initial":             "初期費用上限",
        "chart_value":             "合計バリュー",
        "chart_monthly_x":         "月次予算 ($)",
        "chart_initial_x":         "初期費用上限 ($)",
        "chart_line_title_m":      "月次予算 vs 合計バリュー",
        "chart_line_title_i":      "初期費用上限 vs 合計バリュー",
        "portfolio_btn":           "← ポートフォリオ",
        "reset_btn":               "🔄 リセット",
        "run_opt_btn":             "🚀 最適化を実行",
        "desc":                    "あなたの予算と価値観に基づき、最高のライフスタイルを数理最適化×AIで提案します。",
        # 新UI Step1〜Step4
        "step1_title": "1. 💰 予算と目標の設定",
        "step2_title": "2. 👤 現在のライフスタイル",
        "step3_title": "3. 🧠 価値観と熱量の分析",
        "step4_title": "4. ⚙️ アイテムの微調整 (Optional)",
        
        # 予算入力
        "know_budget_q": "毎月自由に使える予算（可処分所得）は決まっていますか？",
        "yes_calc": "はい",
        "no_calc": "いいえ、計算する",
        "budget_label": "毎月の予算 ($)",
        "calc_expander": "予算の計算",
        "income_label": "手取り月収 ($)",
        "rent_label": "家賃 ($)",
        "fixed_label": "その他固定費 ($)",
        "calc_result": "算出された予算",
        "initial_budget_label": "初期投資に使える貯金 ($)",
        
        # リスク
        "risk_toggle": "⚠️ 現実的なリスクを考慮する",
        
        # 目標
        "goals_subdir": "🎯 目標設定",
        "target_total_label": "目標貯金金額 ($)",
        "period_label": "目標達成までの期間 (年)",
        
        # ライフスタイル定型(Step2)
        "step2_desc": "あなたに最適な選択肢を絞り込むため、いくつか質問にお答えください。",
        "q_car_necessity": "Q1. 現在のお住まいや生活において、車は必須ですか？",
        "q_own_transport": "Q2. 現在、すでに所有している移動手段はありますか？（複数選択可）",
        "own_ebike": "電動自転車",
        "own_moto": "バイク",
        "q_work_style": "Q3. 現在の働き方はどれに一番近いですか？",
        "q_social": "Q4. 人付き合いや、飲み会などの頻度はどのくらいですか？",
        "q_leisure": "Q5. 休日の主な過ごし方（余暇のスタイル）はどれに一番近いですか？",
        "step_food_title": "2b. 🍽️ 食事・交際（飲み）スタイル",
        "step_food_intro": "米国の約2026年時点の物価をベース（Base $400）に推定食費を計算します。係数は内部ロジックのみで使用します。",
        "food_q_home_title": "自宅での食事の質（ベース単価）",
        "food_q_home_body": "自宅での食事（自炊・テイクアウト）で最も重視するスタイルはどれですか？",
        "food_home_minimalist": "Minimalist：節約優先。セール品やプライベートブランドを中心に",
        "food_home_standard": "Standard：栄養バランスを考え、一般的なスーパーで購入",
        "food_home_health": "Health-conscious：オーガニック・無添加・高品質スーパーなど健康投資",
        "food_home_time": "Time-saving：惣菜・カット野菜・冷凍食品など時短重視",
        "food_q_out_title": "交際・飲みの頻度とトーン（QOL加算）",
        "food_q_out_body": "飲み会・バー・カフェなどの交際支出をどの程度、どんな場で使いますか？",
        "food_freq_01": "週に0〜1回",
        "food_freq_23": "週に2〜3回",
        "food_freq_4p": "週に4回以上",
        "food_q_tone_sub": "主な利用シーン（交際トーン）",
        "food_tone_utility": "Utility：効率重視（軽い一杯・短時間の集まり）",
        "food_tone_casual": "Casual：バランス（居酒屋・バー・カフェでの交流）",
        "food_tone_experience": "Experience：体験重視（特別な店・イベント性の高い会食）",
        "food_q_optional_title": "嗜好品と特定支出",
        "food_q_optional_body": "次の項目に、毎月一定以上の支出がありますか？（複数選択可）",
        "food_opt_alcohol": "アルコール・嗜好品（晩酌・ワインなど、食費と分けて考える項目）",
        "food_opt_supp": "サプリメント・プロテイン（身体づくり・美容への固定投資）",
        "food_opt_diet": "特殊な食事制限（アレルギー、ベジタリアン、ケトジェニックなど食材費が上がる要因）",
        
        # 価値観デプロイ(Step3：心理テスト)
        "step3_desc": "熟練のライフプランナー兼心理学者として、あなたの深層価値観を抽出するための質問を用意しました。",
        "q_time_deploy": "Q1. もし来週、予期せぬ3日間の休暇と自由な$500が与えられたら？",
        "q_risk_deploy": "Q2. 生活費が1.2倍になりました。『最後まで削りたくない』のは？",
        "q_live_deploy": "Q3. あなたが最も『生きてる実感』を覚える瞬間は？",
        "value_discovery_sub": "🧘 Value Discovery（1〜4）",
        "q_jelly_deploy": "Q4. 完璧な栄養を10秒で補給できる『完全無欠のゼリー』が発明されました。あなたの反応は？",
        "q_jelly_a": "A: 迷わず採用！その分の時間を自分のために使いたい。",
        "q_jelly_b": "B: 平日は採用、週末は拒否。特別な日は食も楽しみたい。",
        "q_jelly_c": "C: 検討の余地なし。常に本物の食事を楽しみたい。",
        "q_jelly_d": "D: むしろ、そのゼリーの分を節約して他にお金を使いたい。",
        "freetext_q5_intro": "Q5. 人生で譲れないこだわり、理想の生活、または『推し活』などの特定の情熱について自由に教えてください。",
        "step3_freetext_desc": "人生で譲れないこだわり、理想の生活、または『推し活』などの特定の情熱について自由に教えてください。",
        "freetext_label": "自由記述 (譲れないこだわり)",
        "freetext_placeholder": "例：健康のために自炊はしたいが、移動の自由（車）は絶対に譲れない...",
        "analyzing": "プロファイリング中...",
        "analysis_success": "AIがあなたの深層価値観を推論しました！下のスライダーで最終調整してください。",
        "analysis_fail": "AI分析に失敗しました。手動で設定してください。",
        "analysis_fallback": "AIへの接続に失敗したか、応答を解釈できませんでした。これまでの質問・自由記述から重みを推定してスライダーに反映しました。必要に応じて手で調整してください。",
        "analysis_manual_mode": "AIを使わず、これまでの質問と自由記述から重みを推定して反映しました。",
        "use_ai_for_values": "🤖 AIを使って価値観を反映",
        "reflect_to_slider_btn": "✨ 価値観をスライダーに反映",
        "use_ai_for_optimize": "🤖 AIを使って最適化結果サマリーを作成",
        "ai_summary_off": "AIサマリーはOFFです。数理最適化の結果のみ表示しています。",
        "w_subdir": "⚖️ 価値観の重み (1〜10)",
        
        # アイテム修正(Step4)
        "item_review_expander": "AIが補正した選択肢のリストを確認・微調整する",
        "item_review_info": "Step 2・2bの回答に基づき、不要なものは優先度0に、所有済みの場合は初期費用が0に自動補正されています。",
        "mandatory_label": "必須",
        "col_ic": "初期コスト",
        "col_mc": "月次コスト",
        "opt_no_candidates": "候補アイテムがありません。Step 4 で少なくとも1件、優先度を1以上にするか必須にしてください。",
        "opt_best_effort_zero_food": "ベストエフォート: 食費の可変枠（Stage1/2）を0にして再計算しました。",
        "opt_best_effort_transport": "ベストエフォート: 「移動手段を1つ選ぶ」制約を外して再計算しました（移動ゼロも許容）。",
    },
    "en": {
        "portfolio_btn":            "🔗 View Portfolio",
        "portfolio_label":          "Portfolio",
        "title":                   "💰 The Life-Value Optimizer",
        "caption":                 "Maximize your life quality within a limited budget",
        "step1":                   "Step 1: About You",
        "age":                     "Age",
        "gender":                  "Gender",
        "gender_options":          ["Prefer not to say", "Male", "Female", "Other"],
        "family":                  "Household",
        "family_options":          ["Single", "Couple", "Couple + 1 Kid", "Couple + 2 Kids", "Couple + 3 Kids", "Couple + 4 Kids", "Other"],
        "monthly_income":          "Monthly Income (after tax) ($)",
        "fixed_costs_title":       "Fixed Costs (monthly necessities)",
        "rent":                    "Rent / Mortgage ($)",
        "utilities":               "Utilities (Electric/Gas/Water) ($)",
        "internet":                "Internet & Phone ($)",
        "groceries":               "Groceries (basic) ($)",
        "health_insurance_fixed":  "Health Insurance ($)",
        "other_fixed":             "Other Fixed Costs ($)",
        "disposable_income":       "Disposable Income (auto-calculated)",
        "disposable_income_help":  "Income − Fixed costs. This becomes your monthly budget for optimization.",
        "total_budget":            "Initial Cost Limit ($)",
        "total_budget_help":       "Total limit for one-time purchases (car, appliances, etc.)",
        "step2":                   "Step 2: Goal Setting",
        "savings_goal":            "Savings Goal ($)",
        "savings_period":          "Target Period",
        "monthly_savings_cap":     "Monthly savings target: ${}/month",
        "priority":                "Value Weights",
        "goal_type":               "Goal Type",
        "goal_options":            ["Live Well Now", "Build for the Future", "Health & Longevity", "Growth & Career", "Custom"],
        "w_health":                "💪 Health & Vitality",
        "w_connections":           "🔗 Relationships",
        "w_freedom":               "🕐 Freedom & Time",
        "w_growth":                "🎯 Growth & Purpose",
        "w_savings":               "💰 Security & Savings",
        "w_food":                  "🍳 Food (experience & authenticity)",
        "step_lifestyle":          "Step 2.5: Future Income Projection",
        "income_increase":         "Monthly Income Increase ($)",
        "income_years":            "Expected in (years)",
        "income_reason":           "Reason",
        "step3":                   "Step 3: Item Selection",
        "step3_caption":           "Items with a priority number become optimization candidates (0 = excluded). You can edit costs to match your situation.",
        "col_name":                "Item",
        "col_initial":             "Initial($)",
        "col_monthly":             "Monthly($)",
        "col_health":              "💪",
        "col_connections":         "🔗",
        "col_freedom":             "🕐",
        "col_growth":              "🎯",
        "col_priority":            "Priority",
        "col_mandatory":           "Must",
        "col_note":                "Note",
        "deactivate_all":          "🔴 All Off",
        "activate_all":            "🟢 Reset",
        "ai_item_placeholder":     "Enter item name (e.g. Gym, Car)",
        "ai_complete_button":      "🤖 AI Add",
        "ai_summary_title":        "🤖 AI Summary",
        "ai_error_complete":       "AI completion failed. Please fill in manually.",
        "ai_error_summary":        "Failed to generate summary.",
        "risk_toggle":             "Consider realistic risk costs",
        "risk_title":              "⚠️ Risk Cost Estimate",
        "risk_caption":            "Estimated out-of-pocket costs not covered by insurance. You can edit these values.",
        "risk_col_category":       "Category",
        "risk_col_cost":           "Monthly Cost($)",
        "risk_effective":          "Effective monthly budget after risk costs",
        "risk_categories": {
            "medical":    "Medical Out-of-Pocket (copay etc.)",
            "housing":    "Housing Repair",
            "car_repair": "Car Repair",
            "education":  "Education",
            "emergency":  "Emergency Fund",
        },
        "run_button":              "🚀 Optimize",
        "mandatory_summary_title": "Mandatory & Candidate Cost Summary",
        "must_initial":            "Must: Total Initial",
        "must_monthly":            "Must: Total Monthly",
        "cand_initial":            "Candidates: Total Initial",
        "cand_monthly":            "Candidates: Total Monthly",
        "validation_initial_over": "❌ Mandatory items total initial cost (${:,}) exceeds limit (${:,})",
        "validation_monthly_over": "❌ Mandatory items total monthly cost (${:,}) exceeds effective budget (${:,})",
        "validation_no_transport": "⚠️ No transport candidates selected. Please set a priority for at least one.",
        "result_ok":               "✅ Optimal combination found",
        "result_ng":               "❌ No valid combination found. Please review your budget or mandatory items.",
        "total_initial":           "Total Initial Cost",
        "total_monthly":           "Total Monthly Cost",
        "actual_savings":          "Actual Monthly Savings",
        "savings_rate":            "Savings Goal Rate",
        "shortfall_warn":          "⚠️ **${}/month** short of your savings goal.",
        "selected_items":          "Selected Items",
        "rec_title":               "💡 Next steps to boost your satisfaction",
        "rec_within_budget":       "Can be added within budget",
        "sensitivity_title":       "📊 Sensitivity Analysis",
        "tab_monthly":             "Monthly Budget",
        "tab_initial":             "Initial Cost Limit",
        "chart_value":             "Total Value",
        "chart_monthly_x":         "Monthly Budget ($)",
        "chart_initial_x":         "Initial Cost Limit ($)",
        "chart_line_title_m":      "Monthly Budget vs Total Value",
        "chart_line_title_i":      "Initial Cost Limit vs Total Value",
        "portfolio_btn":           "Portfolio",
        "reset_btn":               "🔄 Reset",
        "run_opt_btn":             "🚀 Run Optimization",
        "desc":                    "Proposing the optimal lifestyle based on your budget and values using mathematical optimization & AI.",
        "step1_title": "1. 💰 Budget & Goals",
        "step2_title": "2. 👤 Current Lifestyle",
        "step3_title": "3. 🧠 Values & Passion",
        "step4_title": "4. ⚙️ Item Review (Optional)",
        "know_budget_q": "Do you know your monthly disposable budget?",
        "yes_calc": "Yes",
        "no_calc": "No, calculate it",
        "budget_label": "Monthly Budget ($)",
        "calc_expander": "Calculate Budget",
        "income_label": "Monthly Net Income ($)",
        "rent_label": "Rent ($)",
        "fixed_label": "Other Fixed Costs ($)",
        "calc_result": "Calculated Budget",
        "initial_budget_label": "Initial Budget ($)",
        "risk_toggle": "⚠️ Consider realistic risks",
        "goals_subdir": "🎯 Goals",
        "target_total_label": "Target Savings Amount ($)",
        "period_label": "Years to achieve goal",
        "step2_desc": "Answer a few questions to help us tailor the options for you.",
        "q_car_necessity": "Q1. Is a car essential for your lifestyle?",
        "q_own_transport": "Q2. What transport do you currently own? (Multiple allowed)",
        "own_ebike": "E-Bike",
        "own_moto": "Motorcycle",
        "q_work_style": "Q3. What is your current work style?",
        "q_social": "Q4. How often do you socialize or go out for drinks?",
        "q_leisure": "Q5. What is your primary leisure style?",
        "step_food_title": "2b. 🍽️ Food & social-drinks style",
        "step_food_intro": "Estimated food spending uses U.S. ~2026 prices as a base (Base $400). Internal coefficients are for the model only.",
        "food_q_home_title": "Home meal quality (base price level)",
        "food_q_home_body": "Which style best matches how you eat at home (cooking and takeout)?",
        "food_home_minimalist": "Minimalist: budget-first, sales and store brands",
        "food_home_standard": "Standard: balanced nutrition, typical grocery stores",
        "food_home_health": "Health-conscious: organic, additive-free, premium grocery quality",
        "food_home_time": "Time-saving: deli meals, pre-cut produce, frozen convenience",
        "food_q_out_title": "Social/drinks spending: frequency and tone (QOL add-on)",
        "food_q_out_body": "How often do you spend on social outings (bars, drinks, cafes), and in what setting?",
        "food_freq_01": "0–1 times per week",
        "food_freq_23": "2–3 times per week",
        "food_freq_4p": "4+ times per week",
        "food_q_tone_sub": "Main social tone",
        "food_tone_utility": "Utility: quick/low-cost meetups and short drinks",
        "food_tone_casual": "Casual: bars, izakaya-style places, cafes with friends",
        "food_tone_experience": "Experience: premium venues and event-like dining/drinks",
        "food_q_optional_title": "Discretionary and special food spending",
        "food_q_optional_body": "Do you spend a meaningful amount each month on any of the following? (Multiple selections allowed)",
        "food_opt_alcohol": "Alcohol and similar (e.g., wine at home—track separately from groceries)",
        "food_opt_supp": "Supplements and protein (fixed spend on fitness or beauty)",
        "food_opt_diet": "Special diets (allergies, vegetarian, keto, etc.—often raise grocery cost)",
        "step3_desc": "We prepare questions to extract your deep values.",
        "q_time_deploy": "Q1. Surprise 3-day vacation and $500. What would you do?",
        "q_risk_deploy": "Q2. Cost of living 1.2x. What is the last thing you cut?",
        "q_live_deploy": "Q3. When do you feel most 'alive'?",
        "value_discovery_sub": "🧘 Value Discovery (1-4)",
        "q_jelly_deploy": "Q4. A perfect-nutrition jelly gives you everything you need in 10 seconds. How do you react?",
        "q_jelly_a": "A: I'd adopt it—I'd use that time for myself.",
        "q_jelly_b": "B: Weekdays yes, weekends no—I still want real meals on special days.",
        "q_jelly_c": "C: Not interested—I always want to enjoy real food.",
        "q_jelly_d": "D: I'd rather save that money and spend it on other things.",
        "freetext_q5_intro": "Q5. Share your non-negotiables, ideal lifestyle, or passions (e.g. fandom).",
        "step3_freetext_desc": "Describe your ideal lifestyle or non-negotiable passion.",
        "freetext_label": "Free Text (Non-negotiable passion)",
        "freetext_placeholder": "e.g., I want to cook at home, but freedom of mobility is absolutely necessary...",
        "analyzing": "Analyzing...",
        "analysis_success": "AI has inferred your deep values! Fine-tune them below.",
        "analysis_fail": "AI analysis failed. Please set manually.",
        "analysis_fallback": "Could not reach the AI or parse its reply. We estimated weights from your answers and free text and applied them to the sliders. Adjust manually if needed.",
        "analysis_manual_mode": "Applied estimated weights from your answers and free text without using AI.",
        "use_ai_for_values": "🤖 Use AI for value reflection",
        "reflect_to_slider_btn": "✨ Reflect values to sliders",
        "use_ai_for_optimize": "🤖 Use AI to generate optimization summary",
        "ai_summary_off": "AI summary is OFF. Showing optimization results only.",
        "w_subdir": "⚖️ Value Weights (1-10)",
        "item_review_expander": "Review AI-adjusted item list",
        "item_review_info": "Items adjusted from your Step 2 and 2b answers.",
        "mandatory_label": "Mandatory",
        "col_ic": "Initial Cost",
        "col_mc": "Monthly Cost",
        "opt_no_candidates": "No candidate items. In Step 4, set priority ≥ 1 for at least one item, or mark one as mandatory.",
        "opt_best_effort_zero_food": "Best effort: re-ran with food variable budget (Stage1/2) set to $0.",
        "opt_best_effort_transport": "Best effort: re-ran without the “pick exactly one transport mode” rule (zero transport allowed).",
    }
}

PRESETS = {
    "ja": {
        "今を豊かに生きる":   {"health": 4, "connections": 7, "freedom": 7, "growth": 4, "savings": 2},
        "将来に備える":       {"health": 3, "connections": 2, "freedom": 3, "growth": 5, "savings": 9},
        "健康に長生きする":   {"health": 9, "connections": 5, "freedom": 4, "growth": 4, "savings": 4},
        "自己成長・キャリア": {"health": 4, "connections": 5, "freedom": 3, "growth": 9, "savings": 5},
        "カスタム":           {"health": 5, "connections": 5, "freedom": 5, "growth": 5, "savings": 5},
    },
    "en": {
        "Live Well Now":        {"health": 4, "connections": 7, "freedom": 7, "growth": 4, "savings": 2},
        "Build for the Future": {"health": 3, "connections": 2, "freedom": 3, "growth": 5, "savings": 9},
        "Health & Longevity":   {"health": 9, "connections": 5, "freedom": 4, "growth": 4, "savings": 4},
        "Growth & Career":      {"health": 4, "connections": 5, "freedom": 3, "growth": 9, "savings": 5},
        "Custom":               {"health": 5, "connections": 5, "freedom": 5, "growth": 5, "savings": 5},
    }
}